version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: telegramBot-container
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: bot-secret
      MYSQL_DATABASE: telegram-bot
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
